import type { NextApiRequest, NextApiResponse } from "next";
import { Post } from "../../../models/post";

const posts: Post[] = [
  {
    id: "0",
    author: "chanunn",
    topic: "Jenosize",
    post: "สมัครงาน front-end",
    like: 10,
    point: 10,
    diamont: 20,
    date: "Sat Oct 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "0",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "0",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "1",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 15,
    point: 10,
    diamont: 20,
    date: "Sat Oct 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "1",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "1",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "2",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 20,
    point: 15,
    diamont: 20,
    date: "Sat Oct 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "2",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "2",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "3",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 12,
    point: 15,
    diamont: 20,
    date: "Sat Oct 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "3",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "3",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "4",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 12,
    point: 15,
    diamont: 20,
    date: "Sat Oct 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "4",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "4",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "5",
    author: "chanunn",
    topic: "Jenosize",
    post: "สมัครงาน front-end",
    like: 10,
    point: 10,
    diamont: 20,
    date: "Mon Oct 31 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "5",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "5",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "6",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 15,
    point: 10,
    diamont: 20,
    date: "Mon Oct 31 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "6",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "6",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "7",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 20,
    point: 15,
    diamont: 20,
    date: "Tue Nov 01 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "7",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "7",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "8",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 12,
    point: 15,
    diamont: 20,
    date: "Tue Nov 01 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "8",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "8",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "9",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 12,
    point: 15,
    diamont: 20,
    date: "Wed Nov 02 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "9",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "9",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "10",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 12,
    point: 15,
    diamont: 20,
    date: "Wed Nov 03 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "10",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "10",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "11",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 03 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "11",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "11",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "12",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 04 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "12",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "12",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "13",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 04 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "13",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "13",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "14",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 05 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "14",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "14",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "15",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 05 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "15",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "15",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "16",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 06 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "16",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "16",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "17",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 07 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "17",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "17",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "18",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 08 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "18",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "18",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "19",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 08 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "19",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "19",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "20",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 19,
    point: 15,
    diamont: 20,
    date: "Wed Nov 09 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "20",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "20",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "21",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 10 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "21",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "21",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "22",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 11 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "22",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "22",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "23",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 12 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "23",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "23",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "24",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 13 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "24",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "24",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "25",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 13 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "25",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "25",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "26",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 14 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "26",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "26",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "27",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 15 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "27",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "27",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "28",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 5,
    point: 15,
    diamont: 20,
    date: "Wed Nov 16 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "28",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "28",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "29",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 17 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "29",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "29",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "30",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 18 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "30",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "30",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "31",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 18 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "31",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "31",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "32",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 19 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "32",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "32",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "33",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 20 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "33",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "33",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "34",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 21 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "34",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "34",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "35",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 21 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "35",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "35",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "36",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 22 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "36",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "36",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "37",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 23 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "37",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "37",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "38",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 24 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "38",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "38",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "39",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 25 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "39",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "39",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "40",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 25 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "40",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "40",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "41",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 26 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "41",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "41",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "42",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 27 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "42",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "42",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "43",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 28 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "43",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "43",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "44",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 29 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "44",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "44",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
  {
    id: "45",
    author: "yok",
    topic: "next.js typescript",
    post: "posts",
    like: 16,
    point: 15,
    diamont: 20,
    date: "Wed Nov 30 2022 16:00:00 GMT+0700",
    comment: [
      {
        id: "0",
        idPost: "45",
        author: "Anonymous",
        comment: "yesssss",
      },
      {
        id: "1",
        idPost: "45",
        author: "Anonymous",
        comment: "yeahh",
      },
    ],
  },
];

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const { id } = req.query;
  const result = posts.filter((post) => {
   return post.id === id;
  });
  res.status(200).json(result);
}
